env: dev
pid: ""
level: 4
log: /var/log/artifactory.log

http:
  main:
    addr: 127.0.0.1:10011

mysql:
  - name: main
    host: localhost
    port: 3306
    schema: artifactory
    user: artifactory
    password: "new-artifactory-user-passwd"
    timezone: UTC
    txisolevel: ""
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
    maxidleconn: 5
    maxopenconn: 5
    interpolateparams: false
    maxconnttl: 50s
    timeout: 5s
    readtimeout: 5s
    writetimeout: 5s
    other_params: ""
mysql_migrate:
  - pool: main
    dir: "/var/lib/artifactory/migrations/"

store_providers:
  - name: Local
    type: local
    code: loc
    prefix: ""
    setting: "/var/lib/artifactory/files"

npm_packages:
  ssl: false
  proxy_cache: "/var/lib/artifactory/npm"
